// High-fidelity fallback & development data matching db/seed.sql

import { Category, Product, Testimonial, Enquiry } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Beds', slug: 'beds', description: 'Solid teakwood bedframes with floating headboards and heirloom joinery', display_order: 1, product_count: 1 },
  { id: 2, name: 'Dining', slug: 'dining', description: 'Heavy-slab live-edge and mortise-tenon teak dining tables & benches', display_order: 2, product_count: 1 },
  { id: 3, name: 'Sofas', slug: 'sofas', description: 'Architectural solid teak lounge suites with natural cane and linen accents', display_order: 3, product_count: 1 },
  { id: 4, name: 'Chairs', slug: 'chairs', description: 'Hand-turned planter chairs, dining armchairs, and mid-century teak seats', display_order: 4, product_count: 1 },
  { id: 5, name: 'Tables', slug: 'tables', description: 'Organic coffee tables, teak study desks, and console credenzas', display_order: 5, product_count: 0 },
  { id: 6, name: 'Wardrobes', slug: 'wardrobes', description: 'Traditional louvred armoires and contemporary walk-in teak wardrobes', display_order: 6, product_count: 1 },
  { id: 7, name: 'Doors', slug: 'doors', description: 'Grand carved main entrance doors and courtyard double doors in seasoned teak', display_order: 7, product_count: 1 },
  { id: 8, name: 'Others', slug: 'others', description: 'Bespoke bar units, pooja mandirs, daybeds, and custom architectural elements', display_order: 8, product_count: 0 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'The Malabar Royal Teak Bed',
    slug: 'malabar-royal-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Masterfully sculpted from 100% seasoned Grade-A plantation teak, the Malabar Royal features a gently canted architectural headboard, hidden structural steel reinforcement, and seamless mortise-and-tenon interlocking joints. Designed to be passed down through generations without a single squeak.',
    dimensions: '78" L x 72" W x 46" H (Fits Standard Indian King Mattress: 78" x 72")',
    wood_type: '100% Seasoned Grade-A Central Province Teakwood (Moisture content < 10%)',
    finish_options: 'Natural Hand-Rubbed Oil & Beeswax, Satin Walnut, Honey Teak Lustre',
    customization_options: 'Custom mattress dimensions (King/Queen/California), Hydraulic storage box, Upholstered headboard cushion option',
    starting_price: 84500,
    delivery_time: '3 to 4 weeks (handcrafted upon order)',
    cover_image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 1, product_id: 1, image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Royal Teak Bed Headboard Detail', display_order: 1 },
      { id: 2, product_id: 1, image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=1200&q=80', alt_text: 'Teak Bed frame side joinery and grain', display_order: 2 },
      { id: 3, product_id: 1, image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80', alt_text: 'Bedroom interior setting with Malabar Bed', display_order: 3 },
    ],
  },
  {
    id: 2,
    name: 'Nilgiri 8-Seater Heavy Slab Teak Dining Table',
    slug: 'nilgiri-8-seater-slab-teak-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'An imposing dining centerpiece celebrating the dramatic grain and natural character of seasoned teak. Cut from mature teak logs with butterfly brass inlays and chamfered edges resting on robust double-pedestal trestle legs. Finished with water-repellent organic oil finish.',
    dimensions: '96" L x 40" W x 30" H (Comfortable 8-seater arrangement)',
    wood_type: '100% Solid Heartwood Teak, 2-inch thick seamless continuous plank top',
    finish_options: 'Natural Raw Matte, Deep Espresso, Warm Amber Honey',
    customization_options: 'Custom table length (4 to 12 seaters), Matching teak benches, Optional integrated wire management for conference use',
    starting_price: 118000,
    delivery_time: '4 weeks (crafted in our workshop)',
    cover_image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 4, product_id: 2, image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilgiri Dining Table full overview', display_order: 1 },
      { id: 5, product_id: 2, image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80', alt_text: 'Solid teak wood grain and edge chamfer detail', display_order: 2 },
    ],
  },
  {
    id: 3,
    name: 'Travancore Hand-Woven Cane & Teak 3-Seater Sofa',
    slug: 'travancore-cane-teak-3-seater-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'A classic tribute to tropical modernist architecture. Features a precision sculpted solid teak frame paired with hand-woven natural river cane webbing across the back and arm panels. Equipped with high-resilience 40-density feather-touch foam cushions upholstered in breathable Belgian linen.',
    dimensions: '84" W x 34" D x 32" H (Seat Height: 18")',
    wood_type: '100% Kiln-Dried Solid Teakwood with natural rattan wickerwork',
    finish_options: 'Natural Teak Matte, Dark Tobacco, Vintage Teak Brown',
    customization_options: 'Choice of 2-seater, 3-seater, or L-shape sectional; 40+ fabric and pure leather upholstery choices',
    starting_price: 76000,
    delivery_time: '3 to 4 weeks (handcrafted to order)',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 6, product_id: 3, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Travancore 3-Seater Sofa frontal view', display_order: 1 },
      { id: 7, product_id: 3, image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', alt_text: 'Living room styled setting with teak sofa', display_order: 2 },
    ],
  },
  {
    id: 4,
    name: 'The Calicut Colonial Easy Armchair',
    slug: 'calicut-colonial-easy-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'An authentic homage to the planters chairs of 19th-century estates. Features sweeping ergonomic broad armrests designed for resting tea or a book, hand-woven diamond-pattern cane mesh seat, and subtle brass ferrule accents. Reclines at a natural relaxing lounge angle.',
    dimensions: '34" W x 38" D x 36" H',
    wood_type: '100% Quarter-Sawn Solid Teakwood & Natural Cane Mesh',
    finish_options: 'Hand-Burnished Teak, Walnut Gloss, Heritage Dark Teak',
    customization_options: 'With or without swing-out leg rest extensions, choice of neck roll pillow',
    starting_price: 32500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 8, product_id: 4, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut Colonial Easy Armchair', display_order: 1 },
      { id: 9, product_id: 4, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Armrest joinery and cane weaving detail', display_order: 2 },
    ],
  },
  {
    id: 5,
    name: 'Heritage Archival 3-Door Louvred Teak Wardrobe',
    slug: 'heritage-archival-3-door-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Crafted like the heirloom almirahs of ancestral homes, this 3-door wardrobe features hand-fitted louvred shutters that allow natural air circulation, solid brass mortise locks, deep cedar-lined drawers, and internal concealed hanging rails.',
    dimensions: '72" W x 24" D x 84" H',
    wood_type: '100% Solid Seasoned Teakwood (including inner shelving and drawer sides)',
    finish_options: 'Aged Teak Patina, Natural Matte Sealant, Dark Antique Walnut',
    customization_options: 'Custom internal shelf layout, Safe locker compartment, Full-length mirror on inner door panel',
    starting_price: 145000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 10, product_id: 5, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Heritage Louvred Teak Wardrobe', display_order: 1 },
      { id: 11, product_id: 5, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wardrobe interior cedar shelves and brass hardware', display_order: 2 },
    ],
  },
  {
    id: 6,
    name: 'Chettinad Carved Double Temple Entrance Door',
    slug: 'chettinad-carved-double-entrance-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'A magnificent grand entrance door hand-carved by our senior temple woodcarvers with traditional floral medallions, solid brass lotus studs, and antique hand-forged brass handles. Built from 2.5-inch thick single-grain aged teak to withstand decades of sun and rain.',
    dimensions: '60" W x 96" H (Frame Thickness: 5" x 4")',
    wood_type: 'High-Density Aged Burma Teakwood (Termite & borer proof)',
    finish_options: 'Exterior Weather-Shield Teak Oil, Antique Dark Teak',
    customization_options: 'Custom frame jamb size, provision for digital smart lock, custom carvings/motifs',
    starting_price: null, // Price on request
    delivery_time: '5 to 6 weeks (custom carved)',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [
      { id: 12, product_id: 6, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Chettinad Carved Teak Double Door', display_order: 1 },
      { id: 13, product_id: 6, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Hand-carved floral motif and brass hardware', display_order: 2 },
    ],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    client_name: 'Vikram & Gayatri Menon',
    client_city: 'Bengaluru (Indiranagar)',
    product_purchased: 'Nilgiri 8-Seater Dining Table & Custom Chairs',
    rating: 5,
    review_text: 'We visited their workshop directly in the outskirts. Seeing the raw seasoned teak logs and the master carvers working by hand was an incredible experience. The dining table delivered to our apartment is an absolute centerpiece—heavy, flawlessly jointed, and smooth as silk.',
    client_image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 1,
  },
  {
    id: 2,
    client_name: 'Arunabh Sen',
    client_city: 'Mumbai (Bandra West)',
    product_purchased: 'Custom King Bed & Cane Lounge Chairs',
    rating: 5,
    review_text: 'Finding 100% genuine solid teak without veneer tricks or MDF in Mumbai is nearly impossible. Their team communicated every stage over WhatsApp photos while crafting. It is true heirloom furniture that smells wonderfully of natural wood oil.',
    client_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 2,
  },
  {
    id: 3,
    client_name: 'Dr. Preeti Radhakrishnan',
    client_city: 'Chennai (Adyar)',
    product_purchased: 'Chettinad Carved Main Entrance Door',
    rating: 5,
    review_text: 'Our architects recommended this workshop for our ancestral home renovation. The craftsmanship on the double doors is museum quality. The brass fittings and deep wood carvings give our home an authentic traditional soul. Highly recommend their bespoke service.',
    client_image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 3,
  },
];

export const MOCK_ENQUIRIES: Enquiry[] = [
  {
    id: 1,
    enquiry_type: 'product',
    name: 'Rohit Sharma',
    phone: '+91 98450 12345',
    city: 'Pune',
    product_id: 1,
    product_name: 'The Malabar Royal Teak Bed',
    message: 'Can this king bed be customized with side pull-out drawers and a slightly darker walnut stain? Looking for delivery by end of next month.',
    custom_item_type: null,
    approximate_size: 'King Size (78x72)',
    budget_range: '₹80,000 - ₹1,00,000',
    status: 'New',
    admin_notes: 'Called customer, will send wood finish samples over WhatsApp.',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 2,
    enquiry_type: 'custom',
    name: 'Meera Kapoor',
    phone: '+91 98111 67890',
    city: 'Mumbai',
    product_id: null,
    product_name: null,
    message: 'We want a 10-seater live-edge teak dining table with brass bowtie inlays and 10 matching armchairs with cane backs.',
    custom_item_type: '10-Seater Live Edge Dining Set',
    approximate_size: '120" L x 42" W x 30" H',
    budget_range: 'Above ₹2,50,000',
    status: 'Contacted',
    admin_notes: 'Shared 3 raw slab options from workshop inventory. Awaiting client dimension sign-off.',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 3,
    enquiry_type: 'contact',
    name: 'Aditya Deshmukh',
    phone: '+91 99220 54321',
    city: 'Pune (Kalyani Nagar)',
    product_id: null,
    product_name: null,
    message: 'Would like to visit the Lohegaon workshop this Saturday afternoon with our architect to select timber slabs for our villa.',
    custom_item_type: 'Villa Full Woodworking Package',
    approximate_size: 'Full Bungalow',
    budget_range: 'Above ₹5,00,000',
    status: 'Quoted',
    admin_notes: 'Appointment confirmed for Saturday 3:30 PM.',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
];
