// High-fidelity fallback & development data matching db/seed.sql

import { Category, Product, Testimonial, Enquiry } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Beds', slug: 'beds', description: 'Solid teakwood bedframes with floating headboards and heirloom joinery', display_order: 1, product_count: 10 },
  { id: 2, name: 'Dining', slug: 'dining', description: 'Heavy-slab live-edge and mortise-tenon teak dining tables & benches', display_order: 2, product_count: 10 },
  { id: 3, name: 'Sofas', slug: 'sofas', description: 'Architectural solid teak lounge suites with natural cane and linen accents', display_order: 3, product_count: 10 },
  { id: 4, name: 'Chairs', slug: 'chairs', description: 'Hand-turned planter chairs, dining armchairs, and mid-century teak seats', display_order: 4, product_count: 20 },
  { id: 5, name: 'Tables', slug: 'tables', description: 'Organic coffee tables, teak study desks, and console credenzas', display_order: 5, product_count: 10 },
  { id: 6, name: 'Wardrobes', slug: 'wardrobes', description: 'Traditional louvred armoires and contemporary walk-in teak wardrobes', display_order: 6, product_count: 10 },
  { id: 7, name: 'Doors', slug: 'doors', description: 'Grand carved main entrance doors and courtyard double doors in seasoned teak', display_order: 7, product_count: 10 },
  { id: 8, name: 'Others', slug: 'others', description: 'Bespoke bar units, pooja mandirs, daybeds, and custom architectural elements', display_order: 8, product_count: 10 },
];

export const MOCK_PRODUCTS: Product[] = [
  // ==================== 1. BEDS (10 PRODUCTS) ====================
  {
    id: 101,
    name: 'The Malabar Royal Teak Bed',
    slug: 'malabar-royal-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Masterfully sculpted from 100% seasoned Grade-A plantation teak, the Malabar Royal features a gently canted architectural headboard, hidden structural steel reinforcement, and seamless mortise-and-tenon interlocking joints.',
    dimensions: '78" L x 72" W x 46" H (Fits Standard Indian King Mattress: 78" x 72")',
    wood_type: '100% Seasoned Grade-A Central Province Teakwood (Moisture content < 10%)',
    finish_options: 'Natural Hand-Rubbed Oil & Beeswax, Satin Walnut, Honey Teak Lustre',
    customization_options: 'Custom mattress dimensions (King/Queen/California), Hydraulic storage box, Upholstered headboard cushion option',
    starting_price: 84500,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 1011, product_id: 101, image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Royal Teak Bed', display_order: 1 }],
  },
  {
    id: 102,
    name: 'Kozhikode Low Platform Floating Teak Bed',
    slug: 'kozhikode-floating-platform-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Inspired by Japanese minimalist timber architecture, the Kozhikode platform bed features wide overhanging teak side ledges, concealed recessed legs for a floating silhouette, and integrated solid wood nightstands.',
    dimensions: '84" L x 88" W x 32" H (Platform height: 10")',
    wood_type: '100% Plantation Teakwood with Matte Polyurethane Sealant',
    finish_options: 'Natural Golden Teak, Raw Matte Timber, Dark Espresso',
    customization_options: 'Integrated ambient headboard LED lighting strips, Floating nightstand drawers',
    starting_price: 92000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 1021, product_id: 102, image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=1200&q=80', alt_text: 'Kozhikode Low Platform Teak Bed', display_order: 1 }],
  },
  {
    id: 103,
    name: 'The Mysore Four-Poster Heritage Teak Canopy Bed',
    slug: 'mysore-four-poster-canopy-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'A majestic four-poster canopy bed with hand-turned barley-twist pillars and brass collar accents. Built entirely from thick heartwood teak planks with heirloom lap joinery.',
    dimensions: '82" L x 76" W x 84" H',
    wood_type: '100% Quarter-Sawn Central Province Teakwood',
    finish_options: 'Heritage Amber Gloss, Honey Wax Finish, Vintage Teak Brown',
    customization_options: 'Custom post heights, Brass corner finials, Shear linen curtain rods',
    starting_price: 125000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1031, product_id: 103, image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Canopy Bed', display_order: 1 }],
  },
  {
    id: 104,
    name: 'Travancore Hand-Woven Cane & Teak King Bed',
    slug: 'travancore-hand-woven-cane-teak-king-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Features a hand-turned solid teak frame surrounding breathable hand-woven rattan webbing across the arched headboard panel.',
    dimensions: '80" L x 74" W x 48" H',
    wood_type: '100% Kiln-Dried Teakwood & Natural River Cane',
    finish_options: 'Vintage Teak Matte, Warm Honey, Smoked Walnut',
    customization_options: 'Choice of natural or dark stained cane, Low footboard option',
    starting_price: 88000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1041, product_id: 104, image_url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Travancore Cane Teak Bed', display_order: 1 }],
  },
  {
    id: 105,
    name: 'The Wayanad Hydraulic Storage Teak Bed',
    slug: 'wayanad-hydraulic-storage-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Combines sleek modern teak woodworking with effortless German hydraulic gas-lift underbed storage compartments.',
    dimensions: '79" L x 73" W x 44" H',
    wood_type: 'Solid Plantation Teakwood Frame & Internal Dividers',
    finish_options: 'Natural Teak Satin, Rich Walnut, Dark Mahogany',
    customization_options: 'Dual hydraulic lift sections, Headboard book niche',
    starting_price: 96500,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 1051, product_id: 105, image_url: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Storage Teak Bed', display_order: 1 }],
  },
  {
    id: 106,
    name: 'The Coorg Live-Edge Solid Teak Slab Bed',
    slug: 'coorg-live-edge-solid-teak-slab-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Highlights an organic single-plank live-edge teak headboard slab complete with butterfly brass key joint repairs.',
    dimensions: '82" L x 76" W x 50" H',
    wood_type: '2.5" Thick Single Log Heartwood Teak Slab',
    finish_options: 'Organic Rubbed Beeswax, Clear Matte Sealant',
    customization_options: 'Selection of live-edge raw timber slabs from inventory',
    starting_price: 110000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1061, product_id: 106, image_url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80', alt_text: 'Coorg Live Edge Bed', display_order: 1 }],
  },
  {
    id: 107,
    name: 'The Nilambur Slat-Pattern Teak Queen Bed',
    slug: 'nilambur-slat-pattern-teak-queen-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Contemporary queen bed with vertical slatted teak headboard panels and gently rounded corner posts.',
    dimensions: '78" L x 64" W x 42" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Natural Golden Teak, Light Scandinavian Sealant',
    customization_options: 'Queen or King size option, Matching bedside tables',
    starting_price: 79000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1071, product_id: 107, image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilambur Slat Bed', display_order: 1 }],
  },
  {
    id: 108,
    name: 'The Chettinad Carved Panel Heritage Teak Bed',
    slug: 'chettinad-carved-panel-heritage-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Adorned with traditional lotus flower carvings and brass studs crafted by master temple artisans in South India.',
    dimensions: '82" L x 76" W x 52" H',
    wood_type: 'High-Density Aged Burma Teakwood',
    finish_options: 'Antique Dark Teak, Heritage Amber',
    customization_options: 'Custom family crest or floral medallion carving',
    starting_price: 115000,
    delivery_time: '5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1081, product_id: 108, image_url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80', alt_text: 'Chettinad Carved Bed', display_order: 1 }],
  },
  {
    id: 109,
    name: 'The Anamudi Upholstered Linen & Teak Bed',
    slug: 'anamudi-upholstered-linen-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Combines a rich natural linen padded headboard cushion inset within a thick chamfered teak timber frame.',
    dimensions: '80" L x 74" W x 46" H',
    wood_type: 'Solid Teakwood & Belgian Linen Upholstery',
    finish_options: 'Natural Teak Matte, Dark Tobacco Walnut',
    customization_options: 'Over 30 fabric shade choices for cushion',
    starting_price: 86000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1091, product_id: 109, image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?auto=format&fit=crop&w=1200&q=80', alt_text: 'Anamudi Linen Teak Bed', display_order: 1 }],
  },
  {
    id: 110,
    name: 'The Cochin Low-Profile Mid-Century Teak Bed',
    slug: 'cochin-low-profile-mid-century-teak-bed',
    category_id: 1,
    category_name: 'Beds',
    category_slug: 'beds',
    description: 'Features tapered splayed legs and a gently curved spindle headboard inspired by 1960s Scandinavian woodworking.',
    dimensions: '78" L x 64" W x 38" H',
    wood_type: '100% Quarter-Sawn Seasoned Teak',
    finish_options: 'Natural Scandinavian Teak, Golden Amber',
    customization_options: 'Queen or King size option',
    starting_price: 74500,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 1101, product_id: 110, image_url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Mid-Century Bed', display_order: 1 }],
  },

  // ==================== 2. DINING (10 PRODUCTS) ====================
  {
    id: 201,
    name: 'Nilgiri 8-Seater Heavy Slab Teak Dining Table',
    slug: 'nilgiri-8-seater-slab-teak-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'An imposing dining centerpiece celebrating the dramatic grain and natural character of seasoned teak. Cut from mature teak logs with butterfly brass inlays and chamfered edges.',
    dimensions: '96" L x 40" W x 30" H (Comfortable 8-seater arrangement)',
    wood_type: '100% Solid Heartwood Teak, 2-inch thick continuous plank top',
    finish_options: 'Natural Raw Matte, Deep Espresso, Warm Amber Honey',
    customization_options: 'Custom table length (4 to 12 seaters), Matching teak benches',
    starting_price: 118000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 2011, product_id: 201, image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilgiri Dining Table', display_order: 1 }],
  },
  {
    id: 202,
    name: 'The Wayanad 6-Seater Oval Teak Dining Set',
    slug: 'wayanad-6-seater-oval-teak-dining-set',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Smooth organic oval teak top with sculpted splayed legs and 6 matching dining armchairs upholstered in water-resistant linen fabric.',
    dimensions: '78" L x 42" W x 30" H',
    wood_type: '100% Solid Seasoned Teakwood',
    finish_options: 'Warm Amber Honey, Natural Raw Matte',
    customization_options: '6 or 8 seater option, Custom cushion fabrics',
    starting_price: 98500,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 2021, product_id: 202, image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Oval Dining Set', display_order: 1 }],
  },
  {
    id: 203,
    name: 'The Alleppey Live-Edge Slab Table & Bench Set',
    slug: 'alleppey-live-edge-slab-table-bench-set',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Featuring a single continuous 2.5-inch thick natural live-edge teak slab with butterfly brass keys and a matching full-length solid teak dining bench.',
    dimensions: '84" L x 38" W x 30" H',
    wood_type: '100% Solid Heartwood Teak (Moisture < 9%)',
    finish_options: 'Organic Hand-Rubbed Oil, Satin Sealant',
    customization_options: 'Steel trestle legs or solid teak pedestal legs',
    starting_price: 135000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 2031, product_id: 203, image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80', alt_text: 'Alleppey Live Edge Table', display_order: 1 }],
  },
  {
    id: 204,
    name: 'The Palakkad Extendable 10-Seater Teak Dining Table',
    slug: 'palakkad-extendable-10-seater-teak-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Equipped with a smooth butterfly leaf extension mechanism hidden beneath the tabletop, expanding effortlessly from an 8-seater to a 10-seater.',
    dimensions: '88" to 112" L x 42" W x 30" H',
    wood_type: 'Kiln-Dried Solid Plantation Teakwood',
    finish_options: 'Honey Gold, Natural Satin, Deep Espresso',
    customization_options: 'Extension leaf size, Matching teak armchairs',
    starting_price: 145000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2041, product_id: 204, image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Extendable Table', display_order: 1 }],
  },
  {
    id: 205,
    name: 'The Munnar Round Teak Pedestal Dining Table (6-Seater)',
    slug: 'munnar-round-teak-pedestal-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'A round dining table anchored by a dramatic fluted tambour pedestal base carved from individual teak timber slats.',
    dimensions: '60" Diameter x 30" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Natural Matte, Vintage Dark Teak',
    customization_options: '54" or 60" diameter options, Lazy susan turntable center',
    starting_price: 89000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2051, product_id: 205, image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80', alt_text: 'Munnar Round Pedestal Table', display_order: 1 }],
  },
  {
    id: 206,
    name: 'The Malabar Traditional Trestle Teak Dining Table',
    slug: 'malabar-traditional-trestle-teak-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Classic workshop trestle table design with pinned mortise-and-tenon joints and heavy 3-inch thick turned pedestal legs.',
    dimensions: '90" L x 38" W x 30" H',
    wood_type: '100% Central Province Solid Teak',
    finish_options: 'Heritage Amber, Dark Walnut Oil',
    customization_options: 'Custom tabletop thickness and edge bevel',
    starting_price: 105000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2061, product_id: 206, image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Trestle Table', display_order: 1 }],
  },
  {
    id: 207,
    name: 'The Calicut 4-Seater Compact Teak Dining Set',
    slug: 'calicut-4-seater-compact-teak-dining-set',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Designed for modern urban apartments, featuring a square teak table with chamfered edges and four tuck-in cushioned teak chairs.',
    dimensions: '42" L x 42" W x 30" H',
    wood_type: '100% Plantation Teak',
    finish_options: 'Natural Light Teak, Warm Honey',
    customization_options: 'Cushion fabric color options',
    starting_price: 62000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2071, product_id: 207, image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut 4 Seater Set', display_order: 1 }],
  },
  {
    id: 208,
    name: 'The Kumarakom Glass Top & Teak Grid Dining Table',
    slug: 'kumarakom-glass-top-teak-grid-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Combines a 10mm toughened glass top resting on an architectural teak grid lattice frame that casts beautiful shadows.',
    dimensions: '84" L x 40" W x 30" H',
    wood_type: 'Solid Teak Frame & Toughened Glass',
    finish_options: 'Raw Matte, Espresso Black Teak',
    customization_options: 'Clear or tinted glass top options',
    starting_price: 94000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2081, product_id: 208, image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?auto=format&fit=crop&w=1200&q=80', alt_text: 'Kumarakom Glass Grid Table', display_order: 1 }],
  },
  {
    id: 209,
    name: 'The Cardamom Live-Edge Bar Height Teak Table',
    slug: 'cardamom-live-edge-bar-height-teak-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Counter-height high dining pub table crafted from a thick live-edge teak slab with integrated brass footrest bars.',
    dimensions: '72" L x 28" W x 38" H',
    wood_type: 'Solid Teak Live-Edge Slab & Steel Legs',
    finish_options: 'Natural Teak Oil, Dark Satin',
    customization_options: 'Matching high bar stools',
    starting_price: 78000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2091, product_id: 209, image_url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cardamom Bar Height Table', display_order: 1 }],
  },
  {
    id: 210,
    name: 'The Heritage Brass-Inlay Teak Dining Table',
    slug: 'heritage-brass-inlay-teak-dining-table',
    category_id: 2,
    category_name: 'Dining',
    category_slug: 'dining',
    description: 'Adorned with delicate hand-embedded brass floral inlays along the perimeter of a 6-plank seasoned teak top.',
    dimensions: '90" L x 40" W x 30" H',
    wood_type: '100% Heartwood Teak with Solid Brass Wire Inlay',
    finish_options: 'Heritage Dark Teak, Amber Polish',
    customization_options: 'Custom brass inlay patterns & monogramming',
    starting_price: 128000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 2101, product_id: 210, image_url: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1200&q=80', alt_text: 'Brass Inlay Teak Dining Table', display_order: 1 }],
  },

  // ==================== 3. SOFAS (10 PRODUCTS) ====================
  {
    id: 301,
    name: 'Travancore Hand-Woven Cane & Teak 3-Seater Sofa',
    slug: 'travancore-cane-teak-3-seater-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'A classic tribute to tropical modernist architecture. Features a precision sculpted solid teak frame paired with hand-woven natural river cane webbing across the back and arm panels.',
    dimensions: '84" W x 34" D x 32" H (Seat Height: 18")',
    wood_type: '100% Kiln-Dried Solid Teakwood with natural rattan wickerwork',
    finish_options: 'Natural Teak Matte, Dark Tobacco, Vintage Teak Brown',
    customization_options: 'Choice of 2-seater, 3-seater, or L-shape sectional; 40+ fabric choices',
    starting_price: 76000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 3011, product_id: 301, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Travancore Cane Teak Sofa', display_order: 1 }],
  },
  {
    id: 302,
    name: 'The Malnad Low Architectural L-Sectional Teak Sofa',
    slug: 'malnad-low-architectural-l-sectional-teak-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'A spacious L-shaped modular sectional sofa set on a floating solid teak timber platform with built-in side tables for coffee and books.',
    dimensions: '112" W x 72" D x 28" H',
    wood_type: 'Kiln-Dried Solid Teakwood Frame & Side Tables',
    finish_options: 'Natural Teak Matte, Dark Tobacco Walnut',
    customization_options: 'Left/Right chaise configuration, Custom fabrics',
    starting_price: 142000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 3021, product_id: 302, image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malnad Sectional Teak Sofa', display_order: 1 }],
  },
  {
    id: 303,
    name: 'The Periyar Danish Spindle-Back Teak 2-Seater',
    slug: 'periyar-danish-spindle-back-teak-2-seater',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Crafted with vertical turned teak spindles across the back frame and organic curved armrests. Ultra-comfortable for cozy living rooms or offices.',
    dimensions: '62" W x 32" D x 31" H',
    wood_type: '100% Solid Teakwood & Natural Oil Finish',
    finish_options: 'Honey Gold, Scandinavian Light Teak',
    customization_options: 'Cushion fabric color choices',
    starting_price: 54000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3031, product_id: 303, image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80', alt_text: 'Periyar Danish Spindle Sofa', display_order: 1 }],
  },
  {
    id: 304,
    name: 'The Cochin Mid-Century Sculpted Teak Arm 3-Seater',
    slug: 'cochin-mid-century-sculpted-teak-arm-3-seater',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Highlights fluid teardrop shaped solid teak armrests that taper into sleek turned legs with high-density foam Belgian linen cushions.',
    dimensions: '80" W x 34" D x 30" H',
    wood_type: '100% Quarter-Sawn Teakwood',
    finish_options: 'Natural Golden Teak, Walnut Satin',
    customization_options: '2-seater or 3-seater option, Pure leather upholstery',
    starting_price: 82000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3041, product_id: 304, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Mid-Century Sofa', display_order: 1 }],
  },
  {
    id: 305,
    name: 'The Chettinad Carved Wooden Settee (Diwan Sofa)',
    slug: 'chettinad-carved-wooden-settee-diwan-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Traditional Indian settee with hand-carved teak backrest panels, turned legs, and brass-capped corners for heritage living rooms.',
    dimensions: '72" W x 30" D x 34" H',
    wood_type: 'High-Density Aged Burma Teak',
    finish_options: 'Heritage Dark Teak, Antique Polish',
    customization_options: 'Matching bolster pillows & cotton velvet covers',
    starting_price: 68500,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3051, product_id: 305, image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', alt_text: 'Chettinad Carved Settee', display_order: 1 }],
  },
  {
    id: 306,
    name: 'The Wayanad Modular Teak Corner Sectional',
    slug: 'wayanad-modular-teak-corner-sectional',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'A 5-piece reconfigurable teak sofa system designed with inter-locking timber connectors and weather-resistant canvas fabric.',
    dimensions: '120" W x 96" D x 30" H',
    wood_type: '100% Kiln-Dried Plantation Teak',
    finish_options: 'Natural Teak Oil, Smoked Oak',
    customization_options: 'Add/remove armless middle modules',
    starting_price: 158000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3061, product_id: 306, image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Modular Sectional', display_order: 1 }],
  },
  {
    id: 307,
    name: 'The Nilgiri Slatted Teak Balcony Loveseat',
    slug: 'nilgiri-slatted-teak-balcony-loveseat',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Compact 2-seater outdoor and balcony loveseat built from weather-shield treated teak slats with quick-dry foam cushions.',
    dimensions: '54" W x 28" D x 30" H',
    wood_type: 'Grade-A Outdoor Teakwood',
    finish_options: 'Teak Weather Shield, Raw Teak',
    customization_options: 'Outdoor Sunbrella fabric options',
    starting_price: 46000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3071, product_id: 307, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilgiri Slatted Loveseat', display_order: 1 }],
  },
  {
    id: 308,
    name: 'The Mysore Royal High-Back Teak Sofa',
    slug: 'mysore-royal-high-back-teak-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'An commanding high-back sofa featuring deep button-tufted genuine leather backrest held within a thick dark teak frame.',
    dimensions: '88" W x 36" D x 40" H',
    wood_type: '100% Solid Seasoned Teak & Top-Grain Leather',
    finish_options: 'Heritage Dark Walnut, Royal Honey',
    customization_options: 'Full-grain Italian leather colors',
    starting_price: 112000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3081, product_id: 308, image_url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Royal High-Back Sofa', display_order: 1 }],
  },
  {
    id: 309,
    name: 'The Calicut Rattan & Teak Lounge Suite (1+1+3)',
    slug: 'calicut-rattan-teak-lounge-suite',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Complete 3-piece living room sofa package including one 3-seater sofa and two matching single accent lounge armchairs.',
    dimensions: 'Sofa: 82" W | Chairs: 32" W each',
    wood_type: 'Solid Teak & Handwoven Natural Rattan Mesh',
    finish_options: 'Natural Teak Matte, Honey Polish',
    customization_options: 'Matching teak coffee table package',
    starting_price: 165000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3091, product_id: 309, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut Lounge Suite', display_order: 1 }],
  },
  {
    id: 310,
    name: 'The Anamudi Low Floor-Seating Teak Lounge Sofa',
    slug: 'anamudi-low-floor-seating-teak-lounge-sofa',
    category_id: 3,
    category_name: 'Sofas',
    category_slug: 'sofas',
    description: 'Inspired by Japanese Tatami lounging, featuring a low-slung solid teak platform base with oversized organic feather cushions.',
    dimensions: '90" W x 40" D x 24" H',
    wood_type: '100% Plantation Teakwood',
    finish_options: 'Raw Matte, Natural Oil',
    customization_options: 'Custom cushion firmness levels',
    starting_price: 72000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 3101, product_id: 310, image_url: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1200&q=80', alt_text: 'Anamudi Low Floor Sofa', display_order: 1 }],
  },

  // ==================== 4. CHAIRS (10 PRODUCTS) ====================
  {
    id: 401,
    name: 'The Calicut Colonial Easy Armchair',
    slug: 'calicut-colonial-easy-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'An authentic homage to the planters chairs of 19th-century estates. Features sweeping ergonomic broad armrests designed for resting tea or a book, hand-woven diamond-pattern cane mesh seat.',
    dimensions: '34" W x 38" D x 36" H',
    wood_type: '100% Quarter-Sawn Solid Teakwood & Natural Cane Mesh',
    finish_options: 'Hand-Burnished Teak, Walnut Gloss, Heritage Dark Teak',
    customization_options: 'With or without swing-out leg rest extensions',
    starting_price: 32500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4011, product_id: 401, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut Easy Armchair', display_order: 1 }],
  },
  {
    id: 402,
    name: 'The Kumarakom Sculptural Cane & Teak Dining Chair',
    slug: 'kumarakom-sculptural-cane-teak-dining-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Ergonomically curved solid teak frame featuring hand-woven natural river cane mesh backrest and a memory foam cushioned seat.',
    dimensions: '22" W x 22" D x 34" H',
    wood_type: '100% Seasoned Grade-A Teak & Natural Cane',
    finish_options: 'Natural Matte, Vintage Dark Teak',
    customization_options: 'Set of 4, 6, or 8 chairs; Leather seat options',
    starting_price: 16800,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4021, product_id: 402, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Kumarakom Dining Chair', display_order: 1 }],
  },
  {
    id: 403,
    name: 'The Heritage Solarium Teak Rocking Chair',
    slug: 'heritage-solarium-teak-rocking-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'A traditional rocking chair with turned teak spindles, contoured lumbar support seat, and smooth weighted rockers designed for effortless gliding.',
    dimensions: '28" W x 36" D x 42" H',
    wood_type: '100% Quarter-Sawn Teakwood',
    finish_options: 'Hand-Burnished Teak, Dark Walnut',
    customization_options: 'Custom tufted seat cushion, Engraved brass nameplate',
    starting_price: 28500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4031, product_id: 403, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Heritage Rocking Chair', display_order: 1 }],
  },
  {
    id: 404,
    name: 'The Malabar Folding Teak Deck Lounge Chair',
    slug: 'malabar-folding-teak-deck-lounge-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'A 4-stage reclining outdoor teak lounge chair that folds flat for storage, built with weather-resistant solid brass hinges.',
    dimensions: '26" W x 40" D x 36" H',
    wood_type: '100% Outdoor Plantation Teakwood',
    finish_options: 'Natural Teak Oil Finish, Untreated Raw',
    customization_options: 'Outdoor cushion canvas color options',
    starting_price: 24000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4041, product_id: 404, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Folding Deck Chair', display_order: 1 }],
  },
  {
    id: 405,
    name: 'The Mysore Wishbone Sculpted Teak Dining Chair',
    slug: 'mysore-wishbone-sculpted-teak-dining-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Iconic steam-bent solid teak curved crest rail with Y-back wishbone support and hand-wrapped paper cord woven seat.',
    dimensions: '21" W x 21" D x 30" H',
    wood_type: 'Steam-Bent Solid Teak & Paper Cord',
    finish_options: 'Natural Scandinavian Light, Smoked Black Teak',
    customization_options: 'Natural cord or black cord seat',
    starting_price: 18500,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4051, product_id: 405, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wishbone Teak Chair', display_order: 1 }],
  },
  {
    id: 406,
    name: 'The Wayanad High-Back Executive Teak Desk Chair',
    slug: 'wayanad-high-back-executive-teak-desk-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Ergonomic study chair featuring top-grain padded leather, pneumatic height adjustment, and a solid 5-star teakwood caster wheel base.',
    dimensions: '26" W x 26" D x 44" to 48" H',
    wood_type: 'Solid Teak Frame & Pure Italian Leather',
    finish_options: 'Executive Walnut, Natural Amber',
    customization_options: 'Black, Cognac Brown, or Tan leather',
    starting_price: 36000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4061, product_id: 406, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Executive Teak Desk Chair', display_order: 1 }],
  },
  {
    id: 407,
    name: 'The Cochin Mid-Century Lounge Chair',
    slug: 'cochin-mid-century-lounge-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Slanted rear legs with deep ergonomic foam seating upholstered in textured tweed linen fabric.',
    dimensions: '30" W x 32" D x 31" H',
    wood_type: '100% Kiln-Dried Teakwood',
    finish_options: 'Scandinavian Light Teak, Warm Honey',
    customization_options: '20+ fabric shades',
    starting_price: 29000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4071, product_id: 407, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Mid-Century Chair', display_order: 1 }],
  },
  {
    id: 408,
    name: 'The Palakkad Traditional Carved Wooden Throne Chair',
    slug: 'palakkad-traditional-carved-wooden-throne-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Ornate peacock and floral hand-carved backrest accent chair designed for heritage foyers, altars, and royal seating.',
    dimensions: '32" W x 30" D x 48" H',
    wood_type: 'High-Density Aged Burma Teak',
    finish_options: 'Antique Dark Teak, Heritage Amber',
    customization_options: 'Custom relief carving motif',
    starting_price: 42000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4081, product_id: 408, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Throne Chair', display_order: 1 }],
  },
  {
    id: 409,
    name: 'The Cardamom Bar Stool with Teak Saddle Seat',
    slug: 'cardamom-bar-stool-teak-saddle-seat',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Ergonomically contoured solid teak saddle seat resting on tapered legs reinforced with brass footrest rails.',
    dimensions: '18" W x 14" D x 28" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Natural Teak, Smoked Walnut',
    customization_options: 'Counter height (24") or Bar height (28")',
    starting_price: 14500,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4091, product_id: 409, image_url: 'https://images.unsplash.com/photo-1580481077111-2098ca30e163?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cardamom Bar Stool', display_order: 1 }],
  },
  {
    id: 410,
    name: 'The Alleppey Nesting Teak & Cane Stools (Set of 2)',
    slug: 'alleppey-nesting-teak-cane-stools',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Set of two cylindrical nesting stools with handwoven natural river cane tops and solid teak bases.',
    dimensions: 'Large: 16" Dia x 18" H | Small: 14" Dia x 16" H',
    wood_type: 'Solid Teak & Natural Cane',
    finish_options: 'Natural Teak, Vintage Brown',
    customization_options: 'Cane or upholstered top option',
    starting_price: 19800,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4101, product_id: 410, image_url: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=80', alt_text: 'Alleppey Nesting Stools', display_order: 1 }],
  },
  {
    id: 411,
    name: 'The Windsor Spindle-Back Teak Armchair',
    slug: 'windsor-spindle-back-teak-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Crafted with classic vertical turned spindles, continuous curved teak armrests, and a dark plush cushion seat. Designed for cozy breakfast corners, reading nooks, and accent dining spaces.',
    dimensions: '24" W x 24" D x 36" H (Seat Height: 18")',
    wood_type: '100% Solid Seasoned Grade-A Teakwood',
    finish_options: 'Natural Honey Wax, Golden Amber, Dark Walnut',
    customization_options: 'Choice of velvet or leather seat cushion color',
    starting_price: 22500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-spindle-windsor.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4111, product_id: 411, image_url: '/images/products/chair-spindle-windsor.png', alt_text: 'Windsor Spindle-Back Teak Armchair', display_order: 1 }],
  },
  {
    id: 412,
    name: 'The Scandinavian Low-Profile Teak Patio Lounge Chair',
    slug: 'scandinavian-low-profile-teak-patio-lounge-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Architectural low-slung solid teak lounge chair featuring angled rear legs and thick weather-treated striped linen cushions. Designed for indoor-outdoor patio relaxation and poolside sunrooms.',
    dimensions: '30" W x 34" D x 30" H',
    wood_type: '100% Outdoor Plantation Grade-A Teakwood',
    finish_options: 'Teak Weather Shield, Natural Matte, Raw Teak',
    customization_options: 'Striped or solid Sunbrella outdoor cushion fabric',
    starting_price: 34000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-scandi-patio-lounge.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4121, product_id: 412, image_url: '/images/products/chair-scandi-patio-lounge.png', alt_text: 'Scandinavian Low-Profile Teak Patio Lounge Chair', display_order: 1 }],
  },
  {
    id: 413,
    name: 'The Nordic Geometric Z-Frame Teak Armchair',
    slug: 'nordic-geometric-z-frame-teak-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Sculptural solid teak armchair featuring sharp angular Z-frame armrests, exposed rear vertical timber slats, and high-density grey linen cushions.',
    dimensions: '28" W x 32" D x 31" H',
    wood_type: '100% Quarter-Sawn Kiln-Dried Teakwood',
    finish_options: 'Natural Light Scandinavian Teak, Golden Amber',
    customization_options: 'Grey, Charcoal, or Cream linen cushion options',
    starting_price: 31500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-nordic-z-frame.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4131, product_id: 413, image_url: '/images/products/chair-nordic-z-frame.png', alt_text: 'Nordic Geometric Z-Frame Teak Armchair', display_order: 1 }],
  },
  {
    id: 414,
    name: 'The Chandigarh Compass Cane & Teak Armchair',
    slug: 'chandigarh-compass-cane-teak-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Iconic mid-century modern design featuring inverted V-shaped compass legs, hand-woven natural river cane backrest panel, and a plush upholstered seat.',
    dimensions: '23" W x 24" D x 32" H',
    wood_type: '100% Solid Seasoned Teak & Natural Rattan Webbing',
    finish_options: 'Vintage Teak Brown, Natural Teak Matte, Smoked Walnut',
    customization_options: 'Custom fabric or leather seat upholstery',
    starting_price: 27800,
    delivery_time: '2 weeks',
    cover_image_url: '/images/products/chair-chandigarh-compass-cane.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4141, product_id: 414, image_url: '/images/products/chair-chandigarh-compass-cane.png', alt_text: 'Chandigarh Compass Cane & Teak Armchair', display_order: 1 }],
  },
  {
    id: 415,
    name: 'The Estate Rustic Slatted Teak Garden Armchair',
    slug: 'estate-rustic-slatted-teak-garden-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Heavy-duty outdoor garden armchair built from thick weather-shielded teak timber slats with ergonomic fan-back support and broad flat armrests.',
    dimensions: '32" W x 34" D x 38" H',
    wood_type: 'High-Density Grade-A Outdoor Plantation Teak',
    finish_options: 'Exterior Weather Shield Oil, Untreated Teak',
    customization_options: 'Matching outdoor teak coffee table set',
    starting_price: 26500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-estate-rustic-garden.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4151, product_id: 415, image_url: '/images/products/chair-estate-rustic-garden.png', alt_text: 'Estate Rustic Slatted Teak Garden Armchair', display_order: 1 }],
  },
  {
    id: 416,
    name: 'The Iberian Colonial Leather & Teak Club Chair',
    slug: 'iberian-colonial-leather-teak-club-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'A handsome colonial lounge armchair featuring supple full-grain tan leather upholstery set against a hand-rubbed solid teakwood skeleton with subtle decorative carvings.',
    dimensions: '28" W x 30" D x 34" H',
    wood_type: '100% Seasoned Grade-A Central Province Teakwood',
    finish_options: 'Natural Rubbed Oil, Vintage Walnut, Antiqued Amber',
    customization_options: 'Distressed saddle brown leather, Antique brass nailhead trim',
    starting_price: 34500,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-iberian-colonial-leather.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4161, product_id: 416, image_url: '/images/products/chair-iberian-colonial-leather.png', alt_text: 'Iberian Colonial Leather & Teak Club Chair', display_order: 1 }],
  },
  {
    id: 417,
    name: 'The Heritage Barrel-Back Studded Teak Armchair',
    slug: 'heritage-barrel-back-studded-teak-armchair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Classic curved barrel silhouette constructed from rich teak wood panels, accented with brass stud details and plush tufted leather seating.',
    dimensions: '27" W x 28" D x 33" H',
    wood_type: '100% Solid Plantation Teakwood & Grain Leather',
    finish_options: 'Dark Walnut, Honey Satin, Smoked Espresso',
    customization_options: 'Custom leather dye options, Polished silver studs',
    starting_price: 36000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-heritage-barrel-studded.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4171, product_id: 417, image_url: '/images/products/chair-heritage-barrel-studded.png', alt_text: 'Heritage Barrel-Back Studded Teak Armchair', display_order: 1 }],
  },
  {
    id: 418,
    name: 'The Tuscan Country Cross-Back Teak Dining Chair',
    slug: 'tuscan-country-cross-back-teak-dining-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Rustic yet elegant dining chair with handcrafted curved cross-back splat support, sturdy tapered legs, and a gently contoured solid teak wood seat.',
    dimensions: '20" W x 21" D x 36" H',
    wood_type: '100% Kiln-Dried Solid Teakwood',
    finish_options: 'Natural Matte, Honey Amber, Warm Rustic Oil',
    customization_options: 'Optional woven cane seat pad, Cushion tie-ons',
    starting_price: 18500,
    delivery_time: '2 weeks',
    cover_image_url: '/images/products/chair-tuscan-cross-back.png',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4181, product_id: 418, image_url: '/images/products/chair-tuscan-cross-back.png', alt_text: 'Tuscan Country Cross-Back Teak Dining Chair', display_order: 1 }],
  },
  {
    id: 419,
    name: 'The Artisanal Distressed Slat Teak Accent Chair',
    slug: 'artisanal-distressed-slat-teak-accent-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Contemporary craftsman armchair featuring vertical back slats with a subtle weathered finish and ergonomic armrests for cozy reading nooks.',
    dimensions: '24" W x 26" D x 35" H',
    wood_type: '100% Hand-Distressed Teakwood Timber',
    finish_options: 'Weathered Grey Wash, Antiqued Teak, Rustic Brown',
    customization_options: 'Custom linen seat cushion, Matching footrest ottoman',
    starting_price: 22000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: '/images/products/chair-artisanal-distressed-slat.png',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 4191, product_id: 419, image_url: '/images/products/chair-artisanal-distressed-slat.png', alt_text: 'Artisanal Distressed Slat Teak Accent Chair', display_order: 1 }],
  },
  {
    id: 420,
    name: 'The Zen Minimalist Curved Teak Dining Chair',
    slug: 'zen-minimalist-curved-teak-dining-chair',
    category_id: 4,
    category_name: 'Chairs',
    category_slug: 'chairs',
    description: 'Sleek Scandinavian-Japanese fusion dining chair with a steam-bent curved teak backrest and seamless sculpted wooden joinery.',
    dimensions: '21" W x 22" D x 31" H',
    wood_type: '100% Seasoned Plantation Teakwood',
    finish_options: 'Natural Blonde Teak, Satin Matte Polyurethane, Black Walnut Oil',
    customization_options: 'Upholstered linen pad, Leather seat wrap',
    starting_price: 21500,
    delivery_time: '2 weeks',
    cover_image_url: '/images/products/chair-zen-minimalist-curved.png',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 4201, product_id: 420, image_url: '/images/products/chair-zen-minimalist-curved.png', alt_text: 'Zen Minimalist Curved Teak Dining Chair', display_order: 1 }],
  },

  // ==================== 5. TABLES (10 PRODUCTS) ====================
  {
    id: 501,
    name: 'The Cardamom Hills Sliced Teak Root Coffee Table',
    slug: 'cardamom-hills-sliced-teak-root-coffee-table',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'An artistic coffee table handcrafted from a cross-section of aged teak root featuring natural live voids, resin fills, and solid brass hairpin legs.',
    dimensions: '42" Diameter x 18" H',
    wood_type: 'Reclaimed Solid Teak Root & Brass Legs',
    finish_options: 'Natural Raw Wax, Deep Amber Satin',
    customization_options: 'Custom glass top insert, Brass or matte black leg finish',
    starting_price: 38000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 5011, product_id: 501, image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80', alt_text: 'Teak Root Coffee Table', display_order: 1 }],
  },
  {
    id: 502,
    name: 'The Munnar Executive Teak Study & Work Desk',
    slug: 'munnar-executive-teak-study-work-desk',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Clean-lined executive desk with two seamless soft-close drawers, hidden cable management trough, and a brushed brass modesty strip across the front legs.',
    dimensions: '60" W x 28" D x 30" H',
    wood_type: '100% Solid Seasoned Teakwood',
    finish_options: 'Executive Walnut Stain, Natural Teak',
    customization_options: 'Built-in wireless phone charging pad, Leather blotter inset',
    starting_price: 49500,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 5021, product_id: 502, image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80', alt_text: 'Munnar Teak Executive Desk', display_order: 1 }],
  },
  {
    id: 503,
    name: 'The Nilambur Tambour Slatted Teak Credenza Console',
    slug: 'nilambur-tambour-slatted-teak-credenza-console',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Sideboard credenza with smooth sliding tambour slats carved from solid teak strips, internal adjustable shelving, and brass recessed pulls.',
    dimensions: '66" W x 18" D x 32" H',
    wood_type: '100% Solid Teakwood Slats & Frame',
    finish_options: 'Scandinavian Light Teak, Warm Honey',
    customization_options: 'Internal AV ventilation cutouts, Marble top option',
    starting_price: 68000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 5031, product_id: 503, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilambur Tambour Credenza', display_order: 1 }],
  },
  {
    id: 504,
    name: 'The Wayanad Nested Teak Coffee Tables (Set of 3)',
    slug: 'wayanad-nested-teak-coffee-tables',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'A set of three organic pebble-shaped teak coffee tables of varying heights that tuck under one another.',
    dimensions: 'Large: 36" x 24" x 18" H | Med: 28" x 20" x 16" H | Small: 20" x 16" x 14" H',
    wood_type: '100% Plantation Teakwood',
    finish_options: 'Natural Teak Oil, Dual-Tone Walnut',
    customization_options: 'Set of 2 or 3 tables',
    starting_price: 32000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5041, product_id: 504, image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Nested Tables', display_order: 1 }],
  },
  {
    id: 505,
    name: 'The Cochin Fluted Teak Round Coffee Table',
    slug: 'cochin-fluted-teak-round-coffee-table',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Features a heavy circular teak tabletop anchored by a cylindrical base wrapped in individual vertical fluted teak slats.',
    dimensions: '36" Diameter x 16" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Raw Matte, Smoked Black Teak',
    customization_options: 'Custom diameter (30" to 42")',
    starting_price: 42500,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5051, product_id: 505, image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Fluted Round Table', display_order: 1 }],
  },
  {
    id: 506,
    name: 'The Malabar Tall Entryway Teak Console Table',
    slug: 'malabar-tall-entryway-teak-console-table',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Slim entryway console table featuring two shallow soft-close drawers with antique brass pulls and a lower open slatted display shelf.',
    dimensions: '52" W x 14" D x 34" H',
    wood_type: '100% Quarter-Sawn Teak',
    finish_options: 'Natural Golden Teak, Heritage Amber',
    customization_options: 'Marble or solid teak top option',
    starting_price: 36000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5061, product_id: 506, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Entryway Console', display_order: 1 }],
  },
  {
    id: 507,
    name: 'The Coorg Live-Edge Teak Side Table',
    slug: 'coorg-live-edge-teak-side-table',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Compact sofa side table crafted from a natural 2-inch thick live-edge teak cross-section slab on matte black steel tripod legs.',
    dimensions: '20" Diameter x 22" H',
    wood_type: 'Solid Teak Slab & Powder-Coated Steel',
    finish_options: 'Organic Rubbed Oil, Honey Wax',
    customization_options: 'Brass leg tips',
    starting_price: 18500,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5071, product_id: 507, image_url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80', alt_text: 'Coorg Live Edge Side Table', display_order: 1 }],
  },
  {
    id: 508,
    name: 'The Palakkad Glass Top Teak Display Coffee Table',
    slug: 'palakkad-glass-top-teak-display-coffee-table',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Features a tempered glass top over a shadowbox internal teak drawer designed for displaying coffee table books and collectibles.',
    dimensions: '48" L x 28" D x 18" H',
    wood_type: 'Solid Teak Frame & Toughened Glass',
    finish_options: 'Dark Walnut Stain, Natural Teak',
    customization_options: 'Velvet lining color for display drawer',
    starting_price: 45000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5081, product_id: 508, image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Display Coffee Table', display_order: 1 }],
  },
  {
    id: 509,
    name: 'The Mysore Carved Teak Telephone & Plant Stand',
    slug: 'mysore-carved-teak-telephone-plant-stand',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Heritage turned pedestal accent table with carved floral rim and lower tripod feet for planters or lamps.',
    dimensions: '16" Diameter x 30" H',
    wood_type: '100% Quarter-Sawn Teak',
    finish_options: 'Heritage Amber, Dark Gloss',
    customization_options: 'Brass rim trim option',
    starting_price: 15200,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5091, product_id: 509, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Plant Stand', display_order: 1 }],
  },
  {
    id: 510,
    name: 'The Anamudi Standing Lift-Top Teak Work Desk',
    slug: 'anamudi-standing-lift-top-teak-work-desk',
    category_id: 5,
    category_name: 'Tables',
    category_slug: 'tables',
    description: 'Smooth pneumatic lift-top mechanism that smoothly raises the central teak desk surface for standing work mode.',
    dimensions: '56" W x 26" D x 30" to 42" H',
    wood_type: '100% Seasoned Plantation Teakwood',
    finish_options: 'Natural Light Teak, Smoked Walnut',
    customization_options: 'Integrated power strip & cable ports',
    starting_price: 58000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 5101, product_id: 510, image_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80', alt_text: 'Anamudi Lift-Top Desk', display_order: 1 }],
  },

  // ==================== 6. WARDROBES (10 PRODUCTS) ====================
  {
    id: 601,
    name: 'Heritage Archival 3-Door Louvred Teak Wardrobe',
    slug: 'heritage-archival-3-door-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Crafted like the heirloom almirahs of ancestral homes, this 3-door wardrobe features hand-fitted louvred shutters that allow natural air circulation, solid brass mortise locks, deep cedar-lined drawers.',
    dimensions: '72" W x 24" D x 84" H',
    wood_type: '100% Solid Seasoned Teakwood (including inner shelving)',
    finish_options: 'Aged Teak Patina, Natural Matte Sealant, Dark Antique Walnut',
    customization_options: 'Custom internal shelf layout, Safe locker compartment',
    starting_price: 145000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 6011, product_id: 601, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Heritage Louvred Wardrobe', display_order: 1 }],
  },
  {
    id: 602,
    name: 'The Palakkad Glass & Louvred Teak Armoire',
    slug: 'palakkad-glass-louvred-teak-armoire',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'A majestic 2-door wardrobe combining fluted glass upper panels with bottom louvred shutters, solid brass skeleton key lock.',
    dimensions: '48" W x 24" D x 78" H',
    wood_type: '100% Solid Teakwood & Fluted Safety Glass',
    finish_options: 'Aged Teak Patina, Dark Antique Walnut',
    customization_options: 'Concealed internal drawer chest',
    starting_price: 112000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 6021, product_id: 602, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Teak Armoire', display_order: 1 }],
  },
  {
    id: 603,
    name: 'The Wayanad 4-Door Full-Height Teak Wardrobe',
    slug: 'wayanad-4-door-full-height-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Imposing floor-to-ceiling 4-door master wardrobe featuring full-length mirror inner doors, concealed digital safe compartment, and dual hanging rails.',
    dimensions: '96" W x 24" D x 90" H',
    wood_type: '100% Kiln-Dried Solid Teakwood',
    finish_options: 'Natural Golden Teak, Rich Walnut',
    customization_options: 'Sensor LED interior clothing lighting',
    starting_price: 185000,
    delivery_time: '5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6031, product_id: 603, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad 4-Door Wardrobe', display_order: 1 }],
  },
  {
    id: 604,
    name: 'The Malabar Sliding 2-Door Teak Wardrobe',
    slug: 'malabar-sliding-2-door-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Japanese Shoji inspired top-hung sliding teak door wardrobe ideal for bedrooms with compact clearance space.',
    dimensions: '60" W x 24" D x 82" H',
    wood_type: 'Quarter-Sawn Teak Frame & Soft-Close Track',
    finish_options: 'Natural Teak Satin, Smoked Walnut',
    customization_options: 'Frosted glass or solid timber panels',
    starting_price: 128000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6041, product_id: 604, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Sliding Wardrobe', display_order: 1 }],
  },
  {
    id: 605,
    name: 'The Chettinad Carved Brass-Fitted Teak Almirah',
    slug: 'chettinad-carved-brass-fitted-teak-almirah',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Ancestral heritage almirah featuring hand-carved floral crown moulding, antique brass latch key locks, and deep cedar-scented shelves.',
    dimensions: '54" W x 24" D x 80" H',
    wood_type: 'High-Density Aged Burma Teak',
    finish_options: 'Antique Dark Polish, Heritage Amber',
    customization_options: 'Secret drawer compartment',
    starting_price: 155000,
    delivery_time: '5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6051, product_id: 605, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Chettinad Carved Almirah', display_order: 1 }],
  },
  {
    id: 606,
    name: 'The Cochin 2-Door Compact Teak Wardrobe',
    slug: 'cochin-2-door-compact-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Clean minimalist 2-door wardrobe with recessed teak pulls, upper storage shelf, and stainless hanging rod.',
    dimensions: '42" W x 22" D x 76" H',
    wood_type: '100% Plantation Teak',
    finish_options: 'Scandinavian Light Teak, Warm Honey',
    customization_options: 'Internal drawer add-on',
    starting_price: 88000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6061, product_id: 606, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Compact Wardrobe', display_order: 1 }],
  },
  {
    id: 607,
    name: 'The Anamudi Modular Open Teak Closet Unit',
    slug: 'anamudi-modular-open-teak-closet-unit',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Walk-in closet system with open teak shelving racks, shoe display drawers, and brass clothing rails.',
    dimensions: '80" W x 20" D x 84" H',
    wood_type: 'Kiln-Dried Solid Teak',
    finish_options: 'Natural Teak Oil, Smoked Oak',
    customization_options: 'Modular section add-ons',
    starting_price: 95000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6071, product_id: 607, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Anamudi Open Closet', display_order: 1 }],
  },
  {
    id: 608,
    name: 'The Mysore Royal Teak Armoire with Chest Drawers',
    slug: 'mysore-royal-teak-armoire-chest-drawers',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Features a double-door upper hanging cabinet resting on a 4-drawer lower chest of drawers with solid brass hardware.',
    dimensions: '50" W x 24" D x 80" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Heritage Amber, Dark Walnut',
    customization_options: 'Velvet-lined jewelry top drawer',
    starting_price: 138000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6081, product_id: 608, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Royal Armoire', display_order: 1 }],
  },
  {
    id: 609,
    name: 'The Nilambur Rattan Panel 3-Door Teak Wardrobe',
    slug: 'nilambur-rattan-panel-3-door-teak-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Boasts hand-woven natural cane webbing insets across all 3 door panels to promote continuous air flow for clothing.',
    dimensions: '68" W x 24" D x 82" H',
    wood_type: 'Solid Teak & Natural Rattan Cane',
    finish_options: 'Natural Teak Satin, Honey Polish',
    customization_options: 'Dark or natural cane options',
    starting_price: 162000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6091, product_id: 609, image_url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilambur Rattan Wardrobe', display_order: 1 }],
  },
  {
    id: 610,
    name: 'The Coorg Tall Single-Door Teak Storage Wardrobe',
    slug: 'coorg-tall-single-door-teak-storage-wardrobe',
    category_id: 6,
    category_name: 'Wardrobes',
    category_slug: 'wardrobes',
    description: 'Slim single-door teak linen tower featuring 5 adjustable internal timber shelves for bathroom or corridor storage.',
    dimensions: '24" W x 20" D x 78" H',
    wood_type: '100% Solid Seasoned Teak',
    finish_options: 'Natural Golden Teak, Raw Matte',
    customization_options: 'Left or right door hinge opening',
    starting_price: 58000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 6101, product_id: 610, image_url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?auto=format&fit=crop&w=1200&q=80', alt_text: 'Coorg Single Door Wardrobe', display_order: 1 }],
  },

  // ==================== 7. DOORS (10 PRODUCTS) ====================
  {
    id: 701,
    name: 'Chettinad Carved Double Temple Entrance Door',
    slug: 'chettinad-carved-double-entrance-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'A magnificent grand entrance door hand-carved by our senior temple woodcarvers with traditional floral medallions, solid brass lotus studs.',
    dimensions: '60" W x 96" H (Frame Thickness: 5" x 4")',
    wood_type: 'High-Density Aged Burma Teakwood (Termite proof)',
    finish_options: 'Exterior Weather-Shield Teak Oil, Antique Dark Teak',
    customization_options: 'Custom frame jamb size, digital smart lock cutout',
    starting_price: null, // Price on request
    delivery_time: '5 to 6 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 7011, product_id: 701, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Chettinad Carved Entrance Door', display_order: 1 }],
  },
  {
    id: 702,
    name: 'The Malabar Brass-Studded Solid Teak Main Door',
    slug: 'malabar-brass-studded-solid-teak-main-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'A modern architectural main door featuring vertical teak planks embellished with solid brass square studs and a 36-inch vertical brass pull handle.',
    dimensions: '42" W x 84" H x 2.25" Thick',
    wood_type: '100% Weather-Treated Seasoned Teak',
    finish_options: 'Exterior Weather Shield, Natural Matte',
    customization_options: 'Smart lock integration cutouts, Sidelight matching',
    starting_price: 65000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 7021, product_id: 702, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Malabar Solid Teak Main Door', display_order: 1 }],
  },
  {
    id: 703,
    name: 'The Cochin Glass Lattice French Teak Double Doors',
    slug: 'cochin-glass-lattice-french-teak-double-doors',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: '12-pane clear glass french double doors with solid teak wood mullions, ideal for patio entrances and dining room partitions.',
    dimensions: '60" W x 84" H (2.0" Thick frame)',
    wood_type: '100% Kiln-Dried Teak & Beveled Glass',
    finish_options: 'Natural Teak Satin, Pure White Lacquer',
    customization_options: 'Frosted or fluted glass options',
    starting_price: 78000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7031, product_id: 703, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin French Teak Doors', display_order: 1 }],
  },
  {
    id: 704,
    name: 'The Mysore Sunburst Carved Teak Main Door',
    slug: 'mysore-sunburst-carved-teak-main-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Features a dramatic 3D sunburst radial carving across single-grain teak timber with heavy brass mortise handles.',
    dimensions: '44" W x 90" H x 2.5" Thick',
    wood_type: 'High-Density Seasoned Burma Teak',
    finish_options: 'Heritage Dark Teak, Amber Polish',
    customization_options: 'Left or right opening hinge swing',
    starting_price: 72000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7041, product_id: 704, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Sunburst Door', display_order: 1 }],
  },
  {
    id: 705,
    name: 'The Wayanad Minimalist Flush Teak Door with Brass Strip',
    slug: 'wayanad-minimalist-flush-teak-door-brass-strip',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Sleek contemporary main door with vertical quarter-sawn teak wood grain separated by an embedded vertical brass inlay line.',
    dimensions: '38" W x 84" H x 2.0" Thick',
    wood_type: 'Quarter-Sawn Teak & Solid Brass Strip',
    finish_options: 'Natural Matte, Smoked Walnut',
    customization_options: 'Concealed 3D adjustable hinges',
    starting_price: 48000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7051, product_id: 705, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Flush Teak Door', display_order: 1 }],
  },
  {
    id: 706,
    name: 'The Palakkad Traditional Kerala Courtyard Door',
    slug: 'palakkad-traditional-kerala-courtyard-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Recreates the traditional Manigithavam heavy courtyard doors of nalukettu homes with hand-forged antique iron studs & latch.',
    dimensions: '48" W x 84" H (Heavy 3.0" frame)',
    wood_type: '100% Solid Aged Heartwood Teak',
    finish_options: 'Antique Raw Oil, Dark Teak Stain',
    customization_options: 'Matching carved wood door frame (Jamb)',
    starting_price: 82000,
    delivery_time: '4 to 5 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7061, product_id: 706, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Courtyard Door', display_order: 1 }],
  },
  {
    id: 707,
    name: 'The Nilambur Sliding Barn-Style Teak Door',
    slug: 'nilambur-sliding-barn-style-teak-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Sliding interior timber door constructed from horizontal teak planks with top-mounted matte black industrial steel sliding hardware.',
    dimensions: '42" W x 84" H x 1.75" Thick',
    wood_type: 'Kiln-Dried Solid Teak & Steel Rail',
    finish_options: 'Natural Teak Matte, Vintage Espresso',
    customization_options: 'Custom sliding track length & handle design',
    starting_price: 54000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7071, product_id: 707, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilambur Sliding Barn Door', display_order: 1 }],
  },
  {
    id: 708,
    name: 'The Calicut Carved Lotus Motif Bedroom Teak Door',
    slug: 'calicut-carved-lotus-motif-bedroom-teak-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Elegant interior bedroom door featuring 4 raised panels carved with low-relief lotus floral motifs and brass lever handles.',
    dimensions: '36" W x 80" H x 1.75" Thick',
    wood_type: '100% Plantation Seasoned Teak',
    finish_options: 'Honey Polish, Natural Teak Satin',
    customization_options: 'Brass or black lever locksets',
    starting_price: 52000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7081, product_id: 708, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut Bedroom Teak Door', display_order: 1 }],
  },
  {
    id: 709,
    name: 'The Anamudi Louvred Teak Interior Door',
    slug: 'anamudi-louvred-teak-interior-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Full-height open louvre shutter door ensuring continuous natural ventilation for walk-in closets, pantries, and ensuite bathrooms.',
    dimensions: '34" W x 80" H x 1.5" Thick',
    wood_type: 'Solid Teak Slats & Outer Stile Frame',
    finish_options: 'Natural Light Teak, Satin Sealant',
    customization_options: 'Fixed or adjustable louvres',
    starting_price: 42000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7091, product_id: 709, image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', alt_text: 'Anamudi Louvred Door', display_order: 1 }],
  },
  {
    id: 710,
    name: 'The Coorg Double-Leaf Teak Puja Room Door',
    slug: 'coorg-double-leaf-teak-puja-room-door',
    category_id: 7,
    category_name: 'Doors',
    category_slug: 'doors',
    description: 'Specialty double doors for prayer rooms with carved brass bell cutouts and traditional wooden lattice panels.',
    dimensions: '44" W x 80" H (Double Leaf)',
    wood_type: '100% Solid Seasoned Teak & Solid Brass Bells',
    finish_options: 'Heritage Amber, Traditional Golden Polish',
    customization_options: 'Number of hanging brass bells',
    starting_price: 68000,
    delivery_time: '4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 7101, product_id: 710, image_url: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1200&q=80', alt_text: 'Coorg Puja Double Door', display_order: 1 }],
  },

  // ==================== 8. OTHERS (10 PRODUCTS) ====================
  {
    id: 801,
    name: 'The Temple Sanctum Hand-Carved Teak Pooja Mandir',
    slug: 'temple-sanctum-hand-carved-teak-pooja-mandir',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Freestanding teak home shrine featuring intricate gopuram roof carving, double lattice doors with hanging brass bells, brass-lined prasad drawer.',
    dimensions: '36" W x 22" D x 60" H',
    wood_type: '100% Solid Burma Teakwood',
    finish_options: 'Traditional Golden Teak, Heritage Gloss',
    customization_options: 'Custom height & mandir dome motif',
    starting_price: 58000,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 8011, product_id: 801, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Teak Pooja Mandir', display_order: 1 }],
  },
  {
    id: 802,
    name: 'The Malabar Heritage Fold-Out Teak Bar Credenza',
    slug: 'malabar-heritage-fold-out-teak-bar-credenza',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'A compact credenza that opens into a full home bar with stemware brass racks, wine bottle honeycomb slots, mirror backpanel, and solid teak serving counter.',
    dimensions: '40" W x 20" D x 42" H (Opens to 68" W)',
    wood_type: '100% Kiln-Dried Teakwood',
    finish_options: 'Rich Tobacco Teak, Honey Lustre',
    customization_options: 'Integrated wine chiller niche',
    starting_price: 72500,
    delivery_time: '3 to 4 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
    is_featured: 1,
    is_hidden: 0,
    images: [{ id: 8021, product_id: 802, image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80', alt_text: 'Fold-out Teak Bar Credenza', display_order: 1 }],
  },
  {
    id: 803,
    name: 'The Backwater Lounging Teak Daybed (Diwan)',
    slug: 'backwater-lounging-teak-daybed-diwan',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Traditional Indian diwan daybed frame with turned bolster ends, slatted timber support, and cotton velvet mattress upholstery.',
    dimensions: '75" L x 36" W x 28" H',
    wood_type: '100% Quarter-Sawn Solid Teak',
    finish_options: 'Heritage Amber, Dark Walnut',
    customization_options: 'Custom mattress foam density & cover fabric',
    starting_price: 64000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8031, product_id: 803, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Teak Daybed Diwan', display_order: 1 }],
  },
  {
    id: 804,
    name: 'The Wayanad Teak Bookshelf & Display Unit',
    slug: 'wayanad-teak-bookshelf-display-unit',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Architectural open-back bookshelf with staggered solid teak shelves and brass vertical support rods.',
    dimensions: '48" W x 16" D x 72" H',
    wood_type: 'Solid Teak Planks & Brass Support Columns',
    finish_options: 'Natural Teak Satin, Smoked Walnut',
    customization_options: '4 or 5 tier shelf options',
    starting_price: 52000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8041, product_id: 804, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Wayanad Teak Bookshelf', display_order: 1 }],
  },
  {
    id: 805,
    name: 'The Cochin Freestanding Teak Coat & Hat Rack',
    slug: 'cochin-freestanding-teak-coat-hat-rack',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Hand-turned solid teak central pillar with 8 staggered solid brass hooks and a heavy circular weighted base for entry halls.',
    dimensions: '18" Base Dia x 70" H',
    wood_type: 'Solid Turned Teak & Brass Pegs',
    finish_options: 'Natural Golden Teak, Heritage Dark',
    customization_options: 'Umbrella stand base ring add-on',
    starting_price: 18000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8051, product_id: 805, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Cochin Teak Coat Rack', display_order: 1 }],
  },
  {
    id: 806,
    name: 'The Nilambur Carved Teak Shoe Cabinet',
    slug: 'nilambur-carved-teak-shoe-cabinet',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Ventilated 4-tier shoe storage sideboard with hand-slatted louvre doors and top drawer for keys & accessories.',
    dimensions: '36" W x 15" D x 40" H',
    wood_type: '100% Plantation Teak',
    finish_options: 'Scandinavian Light Teak, Warm Amber',
    customization_options: 'Capacity up to 20 pairs of shoes',
    starting_price: 38500,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8061, product_id: 806, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Nilambur Shoe Cabinet', display_order: 1 }],
  },
  {
    id: 807,
    name: 'The Palakkad Teakwood Wall Mirror & Console Shelf',
    slug: 'palakkad-teakwood-wall-mirror-console-shelf',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Arched full-length wall mirror encased in a 3-inch thick chamfered teak timber frame with a bottom floating shelf.',
    dimensions: '30" W x 72" H x 4" D',
    wood_type: '100% Solid Teak Frame & HD Mirror',
    finish_options: 'Natural Teak Matte, Dark Espresso',
    customization_options: 'Wall mount or leaning floor mirror setup',
    starting_price: 26000,
    delivery_time: '2 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8071, product_id: 807, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Palakkad Teak Wall Mirror', display_order: 1 }],
  },
  {
    id: 808,
    name: 'The Coorg Garden Teak 3-Seater Bench',
    slug: 'coorg-garden-teak-3-seater-bench',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Heavy weather-shield treated outdoor park bench crafted with slatted teak seating and sloped ergonomic armrests.',
    dimensions: '66" W x 26" D x 36" H',
    wood_type: 'Grade-A High Density Outdoor Teak',
    finish_options: 'Teak Weather Shield Oil, Raw Natural',
    customization_options: 'Custom engraved brass bench plaque',
    starting_price: 34000,
    delivery_time: '2 to 3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8081, product_id: 808, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Coorg Garden Teak Bench', display_order: 1 }],
  },
  {
    id: 809,
    name: 'The Mysore Carved Teak Partition Screen (Jali Divider)',
    slug: 'mysore-carved-teak-partition-screen',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: '4-panel folding room divider screen featuring hand-carved floral lattice Jali woodwork with double action brass hinges.',
    dimensions: '80" Total W x 72" H (4 Panels @ 20" W each)',
    wood_type: '100% Quarter-Sawn Teak',
    finish_options: 'Heritage Amber, Dark Polish',
    customization_options: '3, 4, or 5 panel folding options',
    starting_price: 44000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8091, product_id: 809, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Mysore Carved Jali Screen', display_order: 1 }],
  },
  {
    id: 810,
    name: 'The Calicut Antique Style Teak Chest (Petti)',
    slug: 'calicut-antique-style-teak-chest-petti',
    category_id: 8,
    category_name: 'Others',
    category_slug: 'others',
    description: 'Authentic Indian timber storage trunk reinforced with hand-forged brass straps, corner brackets, and heavy padlock HASP.',
    dimensions: '42" W x 22" D x 20" H (Doubles as Coffee Table)',
    wood_type: 'High-Density Aged Burma Teak & Brass Hardware',
    finish_options: 'Antique Dark Patina, Natural Oil',
    customization_options: 'Internal removable cedar tray',
    starting_price: 42000,
    delivery_time: '3 weeks',
    cover_image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80',
    is_featured: 0,
    is_hidden: 0,
    images: [{ id: 8101, product_id: 810, image_url: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=80', alt_text: 'Calicut Antique Teak Chest', display_order: 1 }],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    client_name: 'Vikram & Gayatri Menon',
    client_city: 'Bengaluru (Indiranagar)',
    product_purchased: 'Nilgiri 8-Seater Dining Table & Custom Chairs',
    rating: 5,
    review_text: 'We visited their workshop directly in the outskirts. Seeing the raw seasoned teak logs and the master carvers working by hand was an incredible experience. The dining table delivered to our apartment is an absolute centerpiece—heavy, flawlessly jointed, and smooth as silk.',
    client_image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 1,
  },
  {
    id: 2,
    client_name: 'Arunabh Sen',
    client_city: 'Mumbai (Bandra West)',
    product_purchased: 'Custom King Bed & Cane Lounge Chairs',
    rating: 5,
    review_text: 'Finding 100% genuine solid teak without veneer tricks or MDF in Mumbai is nearly impossible. Their team communicated every stage over WhatsApp photos while crafting. It is true heirloom furniture that smells wonderfully of natural wood oil.',
    client_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 2,
  },
  {
    id: 3,
    client_name: 'Dr. Preeti Radhakrishnan',
    client_city: 'Chennai (Adyar)',
    product_purchased: 'Chettinad Carved Main Entrance Door',
    rating: 5,
    review_text: 'Our architects recommended this workshop for our ancestral home renovation. The craftsmanship on the double doors is museum quality. The brass fittings and deep wood carvings give our home an authentic traditional soul. Highly recommend their bespoke service.',
    client_image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    is_featured: 1,
    display_order: 3,
  },
];

export const MOCK_ENQUIRIES: Enquiry[] = [
  {
    id: 1,
    enquiry_type: 'product',
    name: 'Rohit Sharma',
    phone: '+91 98450 12345',
    city: 'Pune',
    product_id: 101,
    product_name: 'The Malabar Royal Teak Bed',
    message: 'Can this king bed be customized with side pull-out drawers and a slightly darker walnut stain? Looking for delivery by end of next month.',
    custom_item_type: null,
    approximate_size: 'King Size (78x72)',
    budget_range: '₹80,000 - ₹1,00,000',
    status: 'New',
    admin_notes: 'Called customer, will send wood finish samples over WhatsApp.',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 2,
    enquiry_type: 'custom',
    name: 'Meera Kapoor',
    phone: '+91 98111 67890',
    city: 'Mumbai',
    product_id: null,
    product_name: null,
    message: 'We want a 10-seater live-edge teak dining table with brass bowtie inlays and 10 matching armchairs with cane backs.',
    custom_item_type: '10-Seater Live Edge Dining Set',
    approximate_size: '120" L x 42" W x 30" H',
    budget_range: 'Above ₹2,50,000',
    status: 'Contacted',
    admin_notes: 'Shared 3 raw slab options from workshop inventory. Awaiting client dimension sign-off.',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 3,
    enquiry_type: 'contact',
    name: 'Aditya Deshmukh',
    phone: '+91 99220 54321',
    city: 'Pune (Kalyani Nagar)',
    product_id: null,
    product_name: null,
    message: 'Would like to visit the Lohegaon workshop this Saturday afternoon with our architect to select timber slabs for our villa.',
    custom_item_type: 'Villa Full Woodworking Package',
    approximate_size: 'Full Bungalow',
    budget_range: 'Above ₹5,00,000',
    status: 'Quoted',
    admin_notes: 'Appointment confirmed for Saturday 3:30 PM.',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
];
